### ISSUE TITLE
Issue in fail screen

### ISSUE THREAD

**Issue by ckilee** [ckilee/cori_quiz#21]
FATAL EXCEPTION: main
01-31 11:29:26.373 5147-5147/frolic.br.coriquiz E/AndroidRuntime: Process: frolic.br.coriquiz, PID: 5147
01-31 11:29:26.373 5147-5147/frolic.br.coriquiz E/AndroidRuntime: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
01-31 11:29:26.373 5147-5147/frolic.br.coriquiz E/AndroidRuntime:     at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1344)
01-31 11:29:26.373 5147-5147/frolic.br.coriquiz E/AndroidRuntime:     at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1362)
01-31 11:29:26.373 5147-5147/frolic.br.coriquiz E/AndroidRuntime:     at android.app.BackStackRecord.commitInternal(BackStackRecord.java:729)
01-31 11:29:26.373 5147-5147/frolic.br.coriquiz E/AndroidRuntime:     at android.app.BackStackRecord.commit(BackStackRecord.java:705)
01-31 11:29:26.373 5147-5147/frolic.br.coriquiz E/AndroidRuntime:     at frolic.br.coriquiz.FailActivity$2.onCompleted(FailActivity.java:161)
01-31 11:29:26.373 5147-5147/frolic.br.coriquiz E/AndroidRuntime:     at com.facebook.GraphRequest$5.run(GraphRequest.java:1368)
01-31 11:29:26.373 5147-5147/frolic.br.coriquiz E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
01-31 11:29:26.373 5147-5147/frolic.br.coriquiz E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
01-31 11:29:26.373 5147-5147/frolic.br.coriquiz E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
01-31 11:29:26.373 5147-5147/frolic.br.coriquiz E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5910)
01-31 11:29:26.373 5147-5147/frolic.br.coriquiz E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
01-31 11:29:26.373 5147-5147/frolic.br.coriquiz E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
01-31 11:29:26.373 5147-5147/frolic.br.coriquiz E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
01-31 11:29:26.373 5147-5147/frolic.br.coriquiz E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

**Comment by ckilee** [comment]
commit 73570b55385aa39b4ace8e219337f91dae221a52
