### ISSUE TITLE
nullpointer exception on escape activity

### ISSUE THREAD

**Issue by ckilee** [ckilee/cori_quiz#22]
01-31 14:30:08.886 18926-18926/frolic.br.coriquiz E/AndroidRuntime: FATAL EXCEPTION: main
01-31 14:30:08.886 18926-18926/frolic.br.coriquiz E/AndroidRuntime: Process: frolic.br.coriquiz, PID: 18926
01-31 14:30:08.886 18926-18926/frolic.br.coriquiz E/AndroidRuntime: java.lang.NullPointerException: replacement == null
01-31 14:30:08.886 18926-18926/frolic.br.coriquiz E/AndroidRuntime:     at java.lang.String.replace(String.java:1223)
01-31 14:30:08.886 18926-18926/frolic.br.coriquiz E/AndroidRuntime:     at frolic.br.coriquiz.BetweenRoundActivity.publishShare(BetweenRoundActivity.java:116)
01-31 14:30:08.886 18926-18926/frolic.br.coriquiz E/AndroidRuntime:     at frolic.br.coriquiz.BetweenRoundActivity.access$300(BetweenRoundActivity.java:29)
01-31 14:30:08.886 18926-18926/frolic.br.coriquiz E/AndroidRuntime:     at frolic.br.coriquiz.BetweenRoundActivity$2.onClick(BetweenRoundActivity.java:101)
01-31 14:30:08.886 18926-18926/frolic.br.coriquiz E/AndroidRuntime:     at android.view.View.performClick(View.java:5076)
01-31 14:30:08.886 18926-18926/frolic.br.coriquiz E/AndroidRuntime:     at android.view.View$PerformClick.run(View.java:20279)
01-31 14:30:08.886 18926-18926/frolic.br.coriquiz E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
01-31 14:30:08.886 18926-18926/frolic.br.coriquiz E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
01-31 14:30:08.886 18926-18926/frolic.br.coriquiz E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
01-31 14:30:08.886 18926-18926/frolic.br.coriquiz E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5910)
01-31 14:30:08.886 18926-18926/frolic.br.coriquiz E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
01-31 14:30:08.886 18926-18926/frolic.br.coriquiz E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
01-31 14:30:08.886 18926-18926/frolic.br.coriquiz E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
01-31 14:30:08.886 18926-18926/frolic.br.coriquiz E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

**Comment by ckilee** [comment]
commit 7a71b8f2615b69fc0d61d54439de5813de5357fe
