### ISSUE TITLE
Fatal Exception on FailActivity

### ISSUE THREAD

**Issue by ckilee** [ckilee/cori_quiz#30]
FATAL EXCEPTION: main
02-04 19:43:28.060 9989-9989/frolic.br.coriquiz E/AndroidRuntime: Process: frolic.br.coriquiz, PID: 9989
02-04 19:43:28.060 9989-9989/frolic.br.coriquiz E/AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONArray org.json.JSONObject.optJSONArray(java.lang.String)' on a null object reference
02-04 19:43:28.060 9989-9989/frolic.br.coriquiz E/AndroidRuntime:     at frolic.br.coriquiz.FailActivity$3.onCompleted(FailActivity.java:163)
02-04 19:43:28.060 9989-9989/frolic.br.coriquiz E/AndroidRuntime:     at com.facebook.GraphRequest$5.run(GraphRequest.java:1368)
02-04 19:43:28.060 9989-9989/frolic.br.coriquiz E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
02-04 19:43:28.060 9989-9989/frolic.br.coriquiz E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
02-04 19:43:28.060 9989-9989/frolic.br.coriquiz E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
02-04 19:43:28.060 9989-9989/frolic.br.coriquiz E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5910)
02-04 19:43:28.060 9989-9989/frolic.br.coriquiz E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
02-04 19:43:28.060 9989-9989/frolic.br.coriquiz E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
02-04 19:43:28.060 9989-9989/frolic.br.coriquiz E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
02-04 19:43:28.060 9989-9989/frolic.br.coriquiz E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

**Comment by ckilee** [comment]
commit 618af7cc6e0ae1944ab9c65dbdb2a3062f60215e
